## Build and test as standard C++ package
xenial-cpp-build:
  stage: build
  image: rduweston/ubuntu-ci:16.04
  script:
    - cd / && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/westonrobot/public/async_port.git
    - cd /async_port && mkdir build && cd build
    - cmake .. && cpack
    - apt-get install -y apt-utils
    - apt-get install ./async_port_0.1.0_amd64.deb
    - cd /$CI_PROJECT_PATH
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . && cpack

bionic-cpp-build:
  stage: build
  image: rduweston/ubuntu-ci:18.04
  script:
    - cd / && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/westonrobot/public/async_port.git
    - cd /async_port && mkdir build && cd build
    - cmake .. && cpack
    - apt-get install -y apt-utils
    - apt-get install ./async_port_0.1.0_amd64.deb
    - cd /$CI_PROJECT_PATH
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . && cpack

focal-cpp-build:
  stage: build
  image: rduweston/ubuntu-ci:20.04
  script:
    - cd / && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/westonrobot/public/async_port.git
    - cd /async_port && mkdir build && cd build
    - cmake .. && cpack
    - apt-get install -y apt-utils
    - apt-get install ./async_port_0.1.0_amd64.deb
    - cd /$CI_PROJECT_PATH
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . && cpack

## Build and test as catkin package
kinetic-catkin-build:
  stage: build
  image: rduweston/ubuntu-ci:kinetic
  script:
    - mkdir -p /catkin_ws/src/ugv_sdk/ugv_sdk && cd /catkin_ws/src && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_init_workspace"
    - cp -r /builds/$CI_PROJECT_PATH /catkin_ws/src/ugv_sdk
    - cd /catkin_ws/src/ugv_sdk
    - cd /catkin_ws/src && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/westonrobot/public/async_port.git
    - cd /catkin_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_make"

kinetic-catkin-isolated-build:
  stage: build
  image: rduweston/ubuntu-ci:kinetic
  script:
    - mkdir -p /catkin_ws/src/ugv_sdk/ugv_sdk && cd /catkin_ws/src && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_init_workspace"
    - cp -r /builds/$CI_PROJECT_PATH /catkin_ws/src/ugv_sdk
    - cd /catkin_ws/src/ugv_sdk 
    - cd /catkin_ws/src && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/westonrobot/public/async_port.git
    - cd /catkin_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_make_isolated --install"

melodic-catkin-build:
  stage: build
  image: rduweston/ubuntu-ci:melodic
  script:
    - mkdir -p /catkin_ws/src/ugv_sdk && cd /catkin_ws/src && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_init_workspace"
    - cp -r /builds/$CI_PROJECT_PATH /catkin_ws/src/ugv_sdk
    - cd /catkin_ws/src/ugv_sdk
    - cd /catkin_ws/src && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/westonrobot/public/async_port.git
    - cd /catkin_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_make"

melodic-catkin-isolated-build:
  stage: build
  image: rduweston/ubuntu-ci:melodic
  script:
    - mkdir -p /catkin_ws/src/ugv_sdk && cd /catkin_ws/src && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_init_workspace"
    - cp -r /builds/$CI_PROJECT_PATH /catkin_ws/src/ugv_sdk
    - cd /catkin_ws/src/ugv_sdk
    - cd /catkin_ws/src && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/westonrobot/public/async_port.git
    - cd /catkin_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_make_isolated --install"

noetic-catkin-build:
  stage: build
  image: rduweston/ubuntu-ci:noetic
  script:
    - mkdir -p /catkin_ws/src/ugv_sdk && cd /catkin_ws/src && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_init_workspace"
    - cp -r /builds/$CI_PROJECT_PATH /catkin_ws/src/ugv_sdk
    - cd /catkin_ws/src/ugv_sdk
    - cd /catkin_ws/src && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/westonrobot/public/async_port.git
    - cd /catkin_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_make"

noetic-catkin-isolated-build:
  stage: build
  image: rduweston/ubuntu-ci:noetic
  script:
    - mkdir -p /catkin_ws/src/ugv_sdk && cd /catkin_ws/src && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_init_workspace"
    - cp -r /builds/$CI_PROJECT_PATH /catkin_ws/src/ugv_sdk
    - cd /catkin_ws/src/ugv_sdk
    - cd /catkin_ws/src && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/westonrobot/public/async_port.git
    - cd /catkin_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_make_isolated --install"